// src/components/sections/Home.tsx
import { useTranslation } from 'react-i18next'
import { SplitText, GradientText } from '@/components/animations'

export default function Home() {
  const { t } = useTranslation()
  const avatarSrc = `${import.meta.env.BASE_URL}assets/pp_Hedi.png`

  return (
    <section
      id="home"
      className="scroll-mt-24 md:scroll-mt-32 min-h-screen flex flex-col md:flex-row items-center justify-center md:justify-between gap-10 md:gap-20 py-16 px-5 md:py-20 md:pt-24 md:pb-16 md:px-10 max-w-6xl mx-auto"
    >
      <div className="flex-1 w-full text-left max-w-2xl md:max-w-xl flex flex-col justify-between min-h-0 self-stretch">
        <p className="text-sm uppercase tracking-[0.2em] sm:tracking-[0.25em] text-[var(--accent)] mt-8 md:mt-0 mb-4 md:mb-6 font-medium">
          Portfolio
        </p>
        <p className="text-xl md:text-lg text-[var(--muted)] mb-3 md:mb-3">
          {t('home.greeting')}
        </p>
        <h1 className="text-5xl md:text-6xl lg:text-7xl font-semibold tracking-tight mb-4 md:mb-5 text-white">
          <SplitText
            text="Hédi Boissard"
            tag="span"
            splitType="chars"
            className="block text-white"
            delay={120}
            duration={1.4}
          />
        </h1>
        <GradientText
          colors={['#5227FF', '#FF9FFC', '#B19EEF']}
          animationSpeed={8}
          showBorder={false}
          className="text-xl md:text-2xl font-medium mb-6 md:mb-8 text-left"
        >
          {t('home.role')}
        </GradientText>
        <p className="text-lg md:text-lg text-[var(--muted)] max-w-lg mb-6 md:mb-10 leading-relaxed md:leading-loose">
          {t('home.description')}
        </p>
        <div className="flex flex-col sm:flex-row flex-wrap gap-4 sm:gap-5 mb-8 md:mb-10">
          <a
            href="#projects"
            className="inline-flex items-center justify-center w-full sm:w-auto px-6 py-3 sm:px-10 sm:py-5 text-base sm:text-lg font-medium bg-[var(--accent)] text-white rounded-full hover:brightness-110 shadow-[0_8px_25px_rgba(56,189,248,0.3)] hover:shadow-[0_8px_30px_rgba(56,189,248,0.45)] transition-all duration-300"
          >
            {t('home.cta_projects')}
          </a>
          <a
            href="#contact"
            className="inline-flex items-center justify-center w-full sm:w-auto px-6 py-3 sm:px-10 sm:py-5 text-base sm:text-lg font-medium border-2 border-[var(--fg)]/30 rounded-full hover:border-[var(--fg)]/50 transition-colors"
          >
            {t('home.cta_contact')}
          </a>
        </div>
        <div className="flex gap-10 text-white">
          <a
            href="https://www.linkedin.com/in/h%C3%A9di-boissard-a994ab25b/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-white hover:opacity-80 transition-opacity p-3 -m-3"
            aria-label="LinkedIn"
          >
            <img src={`${import.meta.env.BASE_URL}assets/Linkedin.svg`} alt="" className="w-8 h-8 md:w-7 md:h-7 brightness-0 invert" />
          </a>
          <a
            href="https://github.com/hediboissard"
            target="_blank"
            rel="noopener noreferrer"
            className="text-white hover:opacity-80 transition-opacity p-3 -m-3"
            aria-label="GitHub"
          >
            <img src={`${import.meta.env.BASE_URL}assets/GitHub.svg`} alt="" className="w-8 h-8 md:w-7 md:h-7 brightness-0 invert" />
          </a>
        </div>
      </div>

      <div className="hidden md:flex flex-1 justify-center md:justify-end min-w-0">
        <div className="w-56 h-56 sm:w-72 sm:h-72 md:w-80 md:h-80 rounded-full overflow-hidden border-2 border-[var(--fg)]/10 shadow-[0_0_60px_rgba(56,189,248,0.15)] ring-4 ring-purple-500/20 flex-shrink-0">
          <img src={avatarSrc} alt="Hédi Boissard" loading="lazy" decoding="async" className="w-full h-full object-cover object-[52%_100%]" />
        </div>
      </div>
    </section>
  )
}

// src/components/Home.vue
<template>
  <section id="home" class="min-h-screen flex items-center justify-center pt-20">
    <div class="max-w-6xl mx-auto px-4 w-full">
      <div class="flex flex-col-reverse md:flex-row items-center justify-between gap-12">
        
        <div class="flex-1 text-center md:text-left space-y-6">
          <h2 class="text-accent font-medium tracking-wide uppercase">Portfolio</h2>
          <h1 class="text-4xl md:text-6xl font-bold leading-tight">
            {{ t('home.greeting') }} <br/>
            <span class="bg-clip-text text-transparent bg-gradient-to-r from-accent to-purple-500">
              Hédi Boissard
            </span>
          </h1>
          
          <div class="h-8 md:h-12 overflow-hidden">
             <p class="text-xl md:text-2xl opacity-80 animate-slideUp">
               {{ t('home.role') }}
             </p>
          </div>

          <p class="opacity-60 max-w-lg mx-auto md:mx-0">
            {{ t('home.description') }}
          </p>

          <div class="flex flex-wrap gap-4 justify-center md:justify-start pt-4">
            <a href="#projects" class="bg-accent hover:bg-accent-dark text-white px-8 py-3 rounded-full transition-all shadow-lg shadow-accent/25">
              {{ t('home.cta_projects') }}
            </a>
            <a href="#contact" class="border border-current px-8 py-3 rounded-full hover:bg-gray-100 dark:hover:bg-white/10 transition-all">
              {{ t('home.cta_contact') }}
            </a>
          </div>

          <div class="flex gap-6 justify-center md:justify-start pt-4">
            <a href="https://linkedin.com/in/hédi-boissard-a994ab25b" target="_blank" class="opacity-60 hover:opacity-100 transition-opacity hover:text-accent">
              <img src="/assets/Linkedin.svg" class="size-6 dark:invert" alt="LinkedIn">
            </a>
            <a href="https://github.com/hediboissard" target="_blank" class="opacity-60 hover:opacity-100 transition-opacity hover:text-accent">
              <img src="/assets/GitHub.svg" class="size-6 dark:invert" alt="GitHub">
            </a>
          </div>
        </div>

        <div class="flex-1 relative flex justify-center">
          <div class="absolute inset-0 bg-gradient-to-tr from-accent to-purple-500 rounded-full blur-[100px] opacity-20 animate-pulse"></div>
          <div class="relative w-64 h-64 md:w-96 md:h-96 rounded-full p-2 border-2 border-gray-200/50 dark:border-white/10 backdrop-blur-sm">
            <img src="/assets/pp_Hedi.jpeg" class="w-full h-full object-cover rounded-full shadow-2xl" alt="Hédi Boissard" />
          </div>
        </div>

      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { useHead } from '@vueuse/head'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

useHead({
  title: 'Hédi Boissard - Portfolio Développeur',
  meta: [
    {
      name: 'description',
      content: 'Développeur Fullstack spécialisé en Vue.js et Node.js.'
    },
    {
      property: 'og:image',
      content: '/assets/pp_Hedi.jpeg' 
    }
  ]
})
</script>

<style scoped>
.animate-slideUp {
  animation: slideUp 0.5s ease-out forwards;
}
@keyframes slideUp {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>
