// src/components/Navbar.vue
<template>
  <header class="fixed w-full top-0 z-50 transition-all duration-300"
          :class="scrolled ? 'bg-primary/80 dark:bg-primary-dark/80 backdrop-blur-md border-b border-gray-200/10' : 'bg-transparent'">
    <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center h-20">
        <a href="#" class="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-accent to-purple-500">HB.</a>

        <div class="hidden md:flex items-center gap-8">
          <ul class="flex gap-6 text-sm font-medium">
            <li v-for="item in menuItems" :key="item.id">
              <a :href="item.href" @click.prevent="scrollToSection(item.href)"
                 class="relative py-2 transition-colors hover:text-accent"
                 :class="activeSection === item.id ? 'text-accent' : 'text-gray-600 dark:text-gray-300'">
                {{ item.name }}
                <span v-if="activeSection === item.id" class="absolute bottom-0 left-1/2 -translate-x-1/2 w-1 h-1 bg-accent rounded-full"></span>
              </a>
            </li>
          </ul>
          <div class="flex items-center gap-4 pl-6 border-l border-gray-200 dark:border-gray-700">
            <button @click="toggleLanguage" class="font-bold text-sm hover:text-accent w-6">{{ locale.toUpperCase() }}</button>
            <button @click="toggleTheme" class="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors">
              <span v-if="theme === 'dark'">☀️</span>
              <span v-else>🌙</span>
            </button>
          </div>
        </div>

        <!-- Mobile Button -->
        <button @click="isOpen = !isOpen" class="md:hidden p-2 text-gray-600 dark:text-white">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </button>
      </div>
    </nav>

    <!-- Mobile Menu -->
    <div v-if="isOpen" class="md:hidden absolute top-20 left-0 w-full bg-primary dark:bg-primary-dark border-b border-gray-200 dark:border-gray-800 p-4 flex flex-col items-center gap-4">
      <a v-for="item in menuItems" :key="item.id" :href="item.href" @click="scrollToSection(item.href)" class="text-lg">{{ item.name }}</a>
      <div class="flex gap-4 mt-4">
        <button @click="toggleLanguage">{{ locale.toUpperCase() }}</button>
        <button @click="toggleTheme">{{ theme === 'dark' ? 'Light' : 'Dark' }}</button>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'

const { t, locale } = useI18n()
const isOpen = ref(false)
const scrolled = ref(false)
const activeSection = ref('home')
const theme = ref(localStorage.getItem('theme') || 'dark')

const menuItems = computed(() => [
  { id: 'home', name: t('nav.home'), href: '#home' },
  { id: 'about', name: t('nav.about'), href: '#about' },
  { id: 'experience', name: t('nav.experience'), href: '#experience' },
  { id: 'projects', name: t('nav.projects'), href: '#projects' },
  { id: 'skills', name: t('nav.skills'), href: '#skills' },
  { id: 'contact', name: t('nav.contact'), href: '#contact' }
])

const toggleLanguage = () => {
  locale.value = locale.value === 'fr' ? 'en' : 'fr'
  localStorage.setItem('locale', locale.value)
}

const toggleTheme = () => {
  theme.value = theme.value === 'dark' ? 'light' : 'dark'
  localStorage.setItem('theme', theme.value)
  document.documentElement.classList.toggle('dark')
}

const scrollToSection = (href: string) => {
  isOpen.value = false
  const el = document.querySelector(href)
  if (el) window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 80, behavior: 'smooth' })
}

const handleScroll = () => {
  scrolled.value = window.scrollY > 20
  const sections = menuItems.value.map(i => i.id)
  for (const s of sections) {
    const el = document.getElementById(s)
    if (el && el.getBoundingClientRect().top >= -100 && el.getBoundingClientRect().top <= 300) {
      activeSection.value = s
      break
    }
  }
}

onMounted(() => {
  if (theme.value === 'dark') document.documentElement.classList.add('dark')
  const savedLocale = localStorage.getItem('locale')
  if (savedLocale) locale.value = savedLocale
  window.addEventListener('scroll', handleScroll)
})
onUnmounted(() => window.removeEventListener('scroll', handleScroll))
</script>

// src/components/Navbar.tsx
import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'

const MENU_IDS = ['home', 'about', 'experience', 'projects', 'skills', 'contact'] as const

export default function Navbar() {
  const { t, i18n } = useTranslation()
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [active, setActive] = useState('home')
  const [hovered, setHovered] = useState<string | null>(null)

  const toggleLang = () => {
    const next = i18n.language === 'fr' ? 'en' : 'fr'
    i18n.changeLanguage(next)
    localStorage.setItem('locale', next)
  }

  const scrollTo = (id: string) => {
    setOpen(false)
    const el = document.getElementById(id)
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  useEffect(() => {
    const onScroll = () => {
      setScrolled(window.scrollY > 16)
      for (const id of MENU_IDS) {
        const el = document.getElementById(id)
        if (el) {
          const { top } = el.getBoundingClientRect()
          if (top >= -80 && top <= 120) {
            setActive(id)
            break
          }
        }
      }
    }
    window.addEventListener('scroll', onScroll)
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const hasBackground = scrolled || open

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        hasBackground ? 'bg-[var(--bg)]/85 backdrop-blur-md border-b border-[var(--fg)]/5' : ''
      }`}
    >
      <nav className="w-full max-w-7xl mx-auto px-6 md:px-10 h-16 flex items-center justify-between gap-12">
        <button
          onClick={() => scrollTo('home')}
          className="text-2xl font-semibold tracking-tight text-[var(--fg)] hover:text-[var(--accent)] transition-colors"
        >
          HB
        </button>

        <div
          className="hidden md:flex items-center gap-8"
          onMouseLeave={() => setHovered(null)}
        >
          {MENU_IDS.map((id) => {
            const isActive = active === id && (hovered === null || hovered === id)
            return (
              <button
                key={id}
                onClick={() => scrollTo(id)}
                onMouseEnter={() => setHovered(id)}
                className={`group relative py-2 text-sm tracking-wide transition-all duration-300 ${
                  isActive ? 'text-[var(--accent)]' : 'text-[var(--muted)] hover:text-[var(--fg)]'
                }`}
              >
                <span className="relative z-10 inline-block">
                  {t(`nav.${id}`)}
                </span>
                <span
                  className={`absolute bottom-0 left-0 h-0.5 rounded-full transition-all duration-300 ease-out ${
                    isActive ? 'w-full bg-[var(--accent)]' : 'w-0 bg-[var(--accent)] group-hover:w-full'
                  }`}
                />
              </button>
            )
          })}
          <div className="flex items-center pl-6 ml-2 border-l border-[var(--fg)]/10">
            <button
              onClick={toggleLang}
              className="text-xs font-medium text-[var(--muted)] hover:text-[var(--fg)] w-7 transition-colors"
            >
              {i18n.language.toUpperCase()}
            </button>
          </div>
        </div>

        <button
          className="md:hidden p-2 text-[var(--fg)]"
          onClick={() => setOpen(!open)}
          aria-label="Menu"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </nav>

      {open && (
        <div className="md:hidden absolute top-16 left-0 right-0 bg-neutral-900/95 backdrop-blur-sm border-b border-[var(--fg)]/10 py-4 px-4 flex flex-col gap-3">
          {MENU_IDS.map((id) => (
            <button
              key={id}
              onClick={() => scrollTo(id)}
              className={`text-left text-sm py-2 px-2 rounded-md transition-colors ${active === id ? 'text-[var(--accent)]' : 'text-[var(--fg)]'}`}
            >
              {t(`nav.${id}`)}
            </button>
          ))}
          <div className="pt-3 mt-2 border-t border-[var(--fg)]/10">
            <button onClick={toggleLang} className="text-sm text-[var(--muted)] hover:text-[var(--fg)]">
              {i18n.language.toUpperCase()}
            </button>
          </div>
        </div>
      )}
    </header>
  )
}
