// src/components/Skills.tsx
import { useTranslation } from 'react-i18next'
import BlurText from './BlurText'
import LogoLoop, { type LogoItem } from './LogoLoop'

const LOGOS: LogoItem[] = [
  { src: '/assets/skills/vue.svg', alt: 'Vue.js', title: 'Vue.js' },
  { src: '/assets/skills/react.svg', alt: 'React', title: 'React' },
  { src: '/assets/skills/nextjs.svg', alt: 'Next.js', title: 'Next.js' },
  { src: '/assets/skills/tailwind.svg', alt: 'Tailwind', title: 'Tailwind CSS' },
  { src: '/assets/skills/typescript.svg', alt: 'TypeScript', title: 'TypeScript' },
  { src: '/assets/skills/html.svg', alt: 'HTML', title: 'HTML' },
  { src: '/assets/skills/css.svg', alt: 'CSS', title: 'CSS' },
  { src: '/assets/skills/node.svg', alt: 'Node.js', title: 'Node.js' },
  { src: '/assets/skills/nestjs.svg', alt: 'NestJS', title: 'NestJS' },
  { src: '/assets/skills/symfony.svg', alt: 'Symfony', title: 'Symfony' },
  { src: '/assets/skills/java.svg', alt: 'Java', title: 'Java' },
  { src: '/assets/skills/python.svg', alt: 'Python', title: 'Python' },
  { src: '/assets/skills/php.svg', alt: 'PHP', title: 'PHP' },
  { src: '/assets/skills/git.svg', alt: 'Git', title: 'Git' },
  { src: '/assets/skills/jira.svg', alt: 'JIRA', title: 'JIRA' },
  { src: '/assets/skills/docker.svg', alt: 'Docker', title: 'Docker' },
  { src: '/assets/skills/devops.svg', alt: 'DevOps', title: 'DevOps' }
]

export default function Skills() {
  const { t } = useTranslation()

  return (
    <section
      id="skills"
      className="scroll-mt-24 md:scroll-mt-32 py-20 md:py-24 px-4 md:px-10"
    >
      <div className="max-w-5xl mx-auto">
        <h2 className="text-2xl md:text-3xl font-semibold tracking-tight text-[var(--fg)] mb-14 md:mb-20">
          <BlurText
            text={t('skills.title')}
            delay={80}
            animateBy="words"
            direction="top"
            as="span"
            className="inline-block"
          />
        </h2>

        <div className="relative h-44 md:h-52">
          <LogoLoop
            logos={LOGOS}
            speed={100}
            direction="left"
            logoHeight={78}
            gap={78}
            pauseOnHover={false}
            fadeOut
            fadeOutColor="var(--bg)"
            scaleOnHover={false}
            ariaLabel="Technologies que j'utilise"
          />
        </div>
      </div>
    </section>
  )
}

// src/components/Skills.vue
<template>
  <section id="skills" class="py-20 bg-secondary/30 dark:bg-secondary-dark/30">
    <div class="max-w-6xl mx-auto px-4">
      <h2 class="text-3xl md:text-4xl font-bold mb-12 text-center">
        {{ t('skills.title') }}
      </h2>

      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        
        <div class="bg-primary dark:bg-primary-dark p-6 rounded-2xl shadow-lg border border-gray-100 dark:border-gray-800">
          <h3 class="text-xl font-bold mb-6 text-accent">{{ t('skills.categories.frontend') }}</h3>
          <div class="grid grid-cols-3 gap-4">
            <div v-for="skill in frontend" :key="skill.name" class="flex flex-col items-center gap-2 group">
              <div class="p-3 bg-secondary dark:bg-secondary-dark rounded-xl group-hover:scale-110 transition-transform shadow-sm">
                <img :src="`/assets/skills/${skill.logo}`" :alt="skill.name" class="w-8 h-8">
              </div>
              <span class="text-sm opacity-70 text-center">{{ skill.name }}</span>
            </div>
          </div>
        </div>

        <div class="bg-primary dark:bg-primary-dark p-6 rounded-2xl shadow-lg border border-gray-100 dark:border-gray-800">
          <h3 class="text-xl font-bold mb-6 text-accent">{{ t('skills.categories.backend') }}</h3>
          <div class="grid grid-cols-3 gap-4">
            <div v-for="skill in backend" :key="skill.name" class="flex flex-col items-center gap-2 group">
              <div class="p-3 bg-secondary dark:bg-secondary-dark rounded-xl group-hover:scale-110 transition-transform shadow-sm">
                <img :src="`/assets/skills/${skill.logo}`" :alt="skill.name" class="w-8 h-8">
              </div>
              <span class="text-sm opacity-70 text-center">{{ skill.name }}</span>
            </div>
          </div>
        </div>

        <div class="bg-primary dark:bg-primary-dark p-6 rounded-2xl shadow-lg border border-gray-100 dark:border-gray-800">
          <h3 class="text-xl font-bold mb-6 text-accent">{{ t('skills.categories.tools') }}</h3>
          <div class="grid grid-cols-3 gap-4">
            <div v-for="skill in tools" :key="skill.name" class="flex flex-col items-center gap-2 group">
              <div class="p-3 bg-secondary dark:bg-secondary-dark rounded-xl group-hover:scale-110 transition-transform shadow-sm">
                <img :src="`/assets/skills/${skill.logo}`" :alt="skill.name" class="w-8 h-8">
              </div>
              <span class="text-sm opacity-70 text-center">{{ skill.name }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const frontend = [
  { name: 'Vue.js', logo: 'vue.svg' },
  { name: 'React', logo: 'react.svg' },
  { name: 'Tailwind', logo: 'tailwind.svg' },
  { name: 'TypeScript', logo: 'typescript.svg' },
  { name: 'HTML', logo: 'html.svg' },
  { name: 'CSS', logo: 'css.svg' }
]

const backend = [
  { name: 'Node.js', logo: 'node.svg' },
  { name: 'Symfony', logo: 'symfony.svg' },
  { name: 'Java', logo: 'java.svg' },
  { name: 'Python', logo: 'python.svg' },
  { name: 'PHP', logo: 'php.svg' },
  { name: 'JavaScript', logo: 'javascript.svg' }
]

const tools = [
  { name: 'Git', logo: 'git.svg' },
  { name: 'JIRA', logo: 'jira.svg' },
  { name: 'Docker', logo: 'docker.svg' },
  { name: 'DevOps', logo: 'devops.svg' },
  { name: 'Design UX/UI', logo: 'design.svg' }
]
</script>
